#!/bin/bash

for i in {1..100}
do

	sed -i 's/QAudio::SampleType/QExtendedAudioFormat::SampleType/' ../code/headers/*.h
	sed -i 's/QAudio::SampleType/QExtendedAudioFormat::SampleType/' ../code/headers/*/*.h
	sed -i 's/QAudio::SampleType/QExtendedAudioFormat::SampleType/' ../code/sources/*.cpp
	sed -i 's/QAudio::SampleType/QExtendedAudioFormat::SampleType/' ../code/sources/*/*.cpp

done
