#!/bin/bash

for i in {1..100}
do

	sed -i 's/QAudioCoder::/QCoder::/' ../code/headers/*/*.h
	sed -i 's/QAudioCoder::/QCoder::/' ../code/headers/*.h
	sed -i 's/QAudioCoder::/QCoder::/' ../code/sources/*/*.cpp
	sed -i 's/QAudioCoder::/QCoder::/' ../code/sources/*.cpp

done
