#!/bin/bash

for i in {1..100}
do

	sed -i 's/QCodecContent/QAudioInfo/' ../code/headers/*/*.h
	sed -i 's/qcodeccontent/qaudioinfo/' ../code/headers/*/*.h
	sed -i 's/QCodecContent/QAudioInfo/' ../code/headers/*.h
	sed -i 's/qcodeccontent/qaudioinfo/' ../code/headers/*.h

	sed -i 's/QCodecContent/QAudioInfo/' ../code/sources/*/*.cpp
	sed -i 's/qcodeccontent/qaudioinfo/' ../code/sources/*/*.cpp
	sed -i 's/QCodecContent/QAudioInfo/' ../code/sources/*.cpp
	sed -i 's/qcodeccontent/qaudioinfo/' ../code/sources/*.cpp


done
