MACRO(HEADER_DIRECTORIES return_list)
	FILE(GLOB_RECURSE header_list *.h)
	FILE(GLOB_RECURSE source_list *.cpp)
	SET(dir_list "")
	FOREACH(file_path ${header_list})
		GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
		SET(dir_list ${dir_list} ${dir_path})
	ENDFOREACH()
	FOREACH(file_path ${source_list})
		GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
		SET(dir_list ${dir_list} ${dir_path})
	ENDFOREACH()
	LIST(REMOVE_DUPLICATES dir_list)
	SET(${return_list} ${dir_list})
ENDMACRO()
