SET(NAME "QAudioCoder")
SET(PACKAGE "qaudiocoder")
SET(VERSION_MAJOR "0")
SET(VERSION_MINOR "1")
SET(VERSION_PATCH "0")
SET(SHORT_DESCRIPTION "Qt audio decoding, encoding and conversion")
SET(LONG_DESCRIPTION "A Qt-based C++ library for audio decoding, encoding and conversion. ")
SET(MAINTAINER "Christoph Stallmann")
SET(EMAIL "qaudiocoder@visore.org")
SET(HOMEPAGE "http://www.visore.org")
SET(INSTALL_LOCATION "usr")
SET(LICENSE "LGPLv3.0")
SET(COPYRIGHT "Copyright (c) 2012 Christoph Stallmann, University of Pretoria")
SET(README_FILE ${CMAKE_CURRENT_SOURCE_DIR}/../ReadMe.txt)
SET(LICENSE_FILE ${CMAKE_CURRENT_SOURCE_DIR}/../License.txt)
